version: "3.7"
services:
  wex-app:
    build: .
    container_name: "docker-app"
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    links:
      - mongodb
  mongodb:
    image: mongo:4.4.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    container_name: "mongodb"
    hostname: "mongodb"
    ports:
      - 27018:27017